version: "3"

services:
  db:
    image: mongo
    ports:
      - "27021:27017"
  api:
    build: .
    ports: 
      - 3031:3000
      - 9231:9229
    links:      
      - db
    volumes:
    - ./:/home/node/app
    #entrypoint: /home/node/app/.docker/entrypoint.sh
    environment:                  
    - CHOKIDAR_USEPOLLING=true
    - PORT=3000
    - MONGO_URI=mongodb://db:27017
    - MONGO_DATABASE=juri
    - SECONDS_TO_EXPIRE_INVITATION=3600
    - AMBIENT=development
    tty: true